<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit47e88b9e89523da76474cdd7e0057f99
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'FedEx\\Utility\\' => 14,
            'FedEx\\Tests\\' => 12,
            'FedEx\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'FedEx\\Utility\\' => 
        array (
            0 => __DIR__ . '/..' . '/jeremy-dunn/php-fedex-api-wrapper/util',
        ),
        'FedEx\\Tests\\' => 
        array (
            0 => __DIR__ . '/..' . '/jeremy-dunn/php-fedex-api-wrapper/tests/FedEx/Tests',
        ),
        'FedEx\\' => 
        array (
            0 => __DIR__ . '/..' . '/jeremy-dunn/php-fedex-api-wrapper/src/FedEx',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit47e88b9e89523da76474cdd7e0057f99::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit47e88b9e89523da76474cdd7e0057f99::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit47e88b9e89523da76474cdd7e0057f99::$classMap;

        }, null, ClassLoader::class);
    }
}
